# Generated by Django 3.0.5 on 2024-03-02 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('Choose One', 'Choose One'), ('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Information Technology', 'Information Technology')], default='Choose One', max_length=100)),
                ('PDFFile', models.FileField(upload_to='PDFLecture/')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.TeacherExtra')),
            ],
        ),
    ]
